apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-web-html
  namespace: jenkins
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head><meta charset="UTF-8"><title>Hello from NKS</title></head>
    <body>
      <h1>Hello, Jenkins Pipeline Web!</h1>
      <p>This page was deployed by a Jenkins pipeline.</p>
    </body>
    </html>

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-web
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-web
  template:
    metadata:
      labels:
        app: hello-web
    spec:
      containers:
      - name: web
        image: python:3.9-slim
        command: ["python3", "-m", "http.server", "9090", "--directory", "/usr/src/app"]
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: html-volume
          mountPath: /usr/src/app
      volumes:
      - name: html-volume
        configMap:
          name: hello-web-html

---

apiVersion: v1
kind: Service
metadata:
  name: hello-web-service
  namespace: jenkins
spec:
  selector:
    app: hello-web
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
  type: NodePort  # 필요에 따라 LoadBalancer/NodePort로 변경 가능
