pipeline {
    agent any
    stages {
        stage('github-clone') {
            steps {
                git branch: 'main', credentialsId: 'git2', url: 'https://github.com/hjkim-uber/uber-test1'
            }
        }
        stage('Deploy hello-web') {
            steps {
                sh 'kubectl apply -f k8s/hello-web.yaml'
            }
        }
    }
}
